name: Deploy Node Application

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: rizz336/needle360-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Clean Up Docker Environment
        run: |
          docker system prune -af --volumes
          docker image prune -af
          docker builder prune -af
          rm -rf /root/.npm/_cacache || true
          df -h
        continue-on-error: true

      - name: Pull Docker Image
        run: docker pull rizz336/needle360-backend:latest

      - name: Stop Existing Container
        run: docker stop needle360-backend-container || true

      - name: Remove Existing Container
        run: docker rm needle360-backend-container || true

      - name: Create or Join Docker Network
        run: docker network create needle360-network || true

      - name: Start MongoDB Container
        run: |
          docker run -d \
            --name mongo-container \
            --restart unless-stopped \
            --network needle360-network \
            -v mongodb_data:/data/db \
            mongo:latest || true

      - name: Run Docker Container
        run: |
          docker run -d \
            -p 4000:4000 \
            --name needle360-backend-container \
            --network needle360-network \
            -e MONGO_URI=mongodb://mongo-container:27017/needle360 \
            -e MONGODB_PASSWORD='${{ secrets.MONGODB_PASSWORD }}' \
            -e STRIPE_SECRET_KEY='${{ secrets.STRIPE_SECRET_KEY }}' \
            -e MAILTRAP_TOKEN='${{ secrets.MAILTRAP_TOKEN }}' \
            -e MAILTRAP_SENDER_EMAIL='${{ secrets.MAILTRAP_SENDER_EMAIL }}' \
            -e MAILTRAP_SENDER_NAME='${{ secrets.MAILTRAP_SENDER_NAME }}' \
            -e PORT=4000 \
            -e CLIENT_URL='https://needle360.online' \
            -e NODE_ENV=production \
            -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            --restart unless-stopped \
            rizz336/needle360-backend:latest

      - name: Verify Container Running
        run: |
          sleep 10
          docker ps -a
          docker logs needle360-backend-container

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to be ready..."
          for i in {1..10}; do
            if curl -s -f http://localhost:4000/health >/dev/null; then
              echo "Backend is ready"
              exit 0
            fi
            echo "Attempt $i: Backend not ready yet"
            sleep 5
          done
          echo "Backend did not become ready after 10 attempts"
          docker logs needle360-backend-container
          exit 1
