name: Deploy Node Application

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: rizz336/needle360-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Clean Up Docker Environment
        run: |
          docker system prune -f
          docker image prune -a -f
          docker builder prune -f
        continue-on-error: true

      - name: Pull Docker Image
        run: docker pull rizz336/needle360-backend:latest

      - name: Stop Existing Container
        run: docker stop needle360-backend-container || true

      - name: Remove Existing Container
        run: docker rm needle360-backend-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 4000:4000 --name needle360-backend-container \
            -e MONGODB_PASSWORD='${{ secrets.MONGODB_PASSWORD }}' \
            -e STRIPE_SECRET_KEY='${{ secrets.STRIPE_SECRET_KEY }}' \
            -e PORT=4000 \
            -e CLIENT_URL='${{ secrets.CLIENT_URL }}' \
            -e NODE_ENV=production \
            --restart unless-stopped \
            rizz336/needle360-backend:latest

      - name: Verify Container Running
        run: docker ps | grep needle360-backend-container
